apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-socket-deployment
spec:
  selector:
    matchLabels:
      app: chat-socket
  replicas: 3
  template:
    metadata:
      labels:
        app: chat-socket
    spec:
      containers:
        - name: chat-socket
          image: jurajmarkesic/chat-socket:f297b0b88a44da802891fa80369fe636e8770f73
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
