apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-socket-deployment
spec:
  selector:
    matchLabels:
      app: chat-socket
  replicas: 3
  template:
    metadata:
      labels:
        app: chat-socket
    spec:
      containers:
        - name: chat-socket
          image: jurajmarkesic/chat-socket:f6ad127493b5ad2e09d9d285d5ce009a5b6a7615
          ports:
            - containerPort: 3005
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
