apiVersion: v1
kind: Service
metadata:
  name: chat-socket-service
  annotations:
    configuration.konghq.com: kong-ingress-config
    konghq.com/override: kong-ingress-config
spec:
  selector:
    app: chat-socket
  type: NodePort
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
      nodePort: 31000
      name: 'socket'
    - protocol: TCP
      port: 3006
      targetPort: 3006
      nodePort: 31001
      name: 'inter-pod-http'
