apiVersion: v1
kind: Service
metadata:
  name: chat-socket-service
spec:
  selector:
    app: chat-socket
  type: NodePort
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
      nodePort: 31000
